cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build:frontend

linting:
  stage: test
  script:
    - npm run tslint

jest:
  stage: test
  script:
    - npm run test
